---
- src: https://github.com/trawick/emptyhammock-role-application
  version: 0.0.5
  name: application
- src: https://github.com/trawick/emptyhammock-role-database
  version: 0.0.2
  name: database
- src: https://github.com/trawick/emptyhammock-role-httpd
  version: 0.0.2
  name: httpd
- src: https://github.com/trawick/emptyhammock-role-logging
  version: 0.0.2
  name: logging
- src: https://github.com/trawick/emptyhammock-role-maintenance
  version: 0.0.5
  name: maintenance
- src: https://github.com/trawick/emptyhammock-role-system-config
  version: 0.0.1
  name: system_config
- src: https://github.com/trawick/emptyhammock-role-system-packages
  version: 0.0.6
  name: system_packages
- src: https://github.com/trawick/emptyhammock-role-users-and-groups
  version: 0.0.3
  name: users_and_groups
- src: https://github.com/trawick/emptyhammock-role-uwsgi
  version: 0.0.4
  name: uwsgi
