---
- hosts: webservers
  become: true
  become_user: postgres
  tasks:
    - postgresql_db:
        name: "{{ project_db }}"
        state: dump
        target: "{{ dumpname }}"
        target_opts: "-Ox"
